export const paramDescriptions: Record<string, string> = {
    shapeCount: "Total number of blobs generated and animated in the simulation.",
    edgePointCount: "Number of points used to define the outline of each blob. Higher values make blobs smoother.",
    minBlobSize: "Minimum radius for each blob. Controls the smallest possible blob size.",
    repelDistance: "Distance at which blobs start to push each other away to avoid overlap.",
    springTension: "How strongly each blob's edge points are pulled back to their original positions, affecting blob elasticity.",
    interactionStrength: "Controls how much blobs influence each other's movement when they get close.",
    damping: "Rate at which blob movement slows down, simulating friction or resistance.",
    speed: "Multiplier for the simulation's animation speed. Higher values make blobs move faster.",
    maxExpansionFactor: "Maximum amount a blob can expand beyond its initial size when interacting with others.",
    containerMargin: "Empty space (in pixels) around the edge of the simulation area.",
    isRoundedContainer: "If enabled, the simulation area is a circle instead of a rectangle.",
    showBorder: "Show or hide the border around the simulation container.",
    restrictedAreaEnabled: "Enable a special area (in the shape of a letter) that blobs will avoid.",
    restrictedAreaLetter: "The character used to define the restricted area that blobs avoid.",
    restrictedAreaSize: "The size (in pixels) of the restricted area letter.",
    fontFamily: "Font family used to render the restricted area letter. Enter the name of any installed font.",
    backgroundColor: "Background color for the simulation in light mode.",
    blobFillColor: "Fill color for blobs in light mode.",
    blobBorderColor: "Border color for blobs in light mode.",
    letterColor: "Color of the restricted area letter in light mode.",
    blobFillOpacity: "Opacity of the blob fill color in light mode. Lower values make blobs more transparent.",
    darkBackgroundColor: "Background color for the simulation in dark mode.",
    darkBlobFillColor: "Fill color for blobs in dark mode.",
    darkBlobBorderColor: "Border color for blobs in dark mode.",
    darkLetterColor: "Color of the restricted area letter in dark mode.",
    darkBlobFillOpacity: "Opacity of the blob fill color in dark mode. Lower values make blobs more transparent."
    // Add descriptions for any other parameters like gravity, restrictedAreaMargin, etc. if they exist
};
